### ISSUE TITLE
Add OKKEX support

### ISSUE THREAD

**Issue by puzanov** [maddevsio/new-para-bot#3]
https://github.com/okcoin-okex/API-docs-OKEx.com

**Comment by puzanov** [comment]
https://github.com/okcoin-okex/API-docs-OKEx.com/issues/38 - waiting

**Comment by puzanov** [comment]
https://www.okex.com/v2/spot/markets/index-tickers?limit=100000000

**Comment by puzanov** [comment]
done

**Comment by hoota** [comment]
@puzanov index-tickers gives only BTC based pairs
